// Language translations
const translations = {
    it: {
        welcome: "LifeTracker ★",
        login: "Accedi",
        register: "Registrati",
        email: "Email",
        password: "Password",
        confirmPassword: "Conferma Password",
        loginButton: "Accedi",
        registerButton: "Registrati",
        logout: "Esci",
        loggingIn: "Accesso in corso...",
        registering: "Registrazione in corso...",
        loginSuccess: "Login effettuato con successo!",
        registerSuccess: "Registrazione completata! Controlla la tua email per confermare l'account.",
        passwordMismatch: "Le password non coincidono",
        logoutError: "Errore durante il logout: ",
        emailPlaceholder: "tua@email.com",
        passwordPlaceholder: "••••••••",
        dashboardTitle: "Area Riservata",
        dashboardText: "Benvenuto nell'area riservata! Questa sezione è visibile solo agli utenti autenticati. Qui puoi gestire il tuo account e accedere a tutte le funzionalità riservate.",
        userEmail: "Email:",
        googleLogin: "Accedi con Google",
        orDivider: "oppure",
        usePersonalEmail: "Utilizza la tua mail personale",
        menuHome: "Tracciamento",
        menuTasks: "Lista attività",
        menuCalendar: "Calendario",
        menuStats: "Statistiche",
        loadingTasks: "Caricamento attività...",
        noTasks: "Nessuna attività trovata",
        tasksSubtitle: "Ecco la lista delle attività che sono disponibili per te e che puoi tracciare",
        trackedActivities: "Attività tracciate",
        addTracking: "Aggiungi un tracciamento",
        loadingCategories: "Caricamento categorie...",
        loadingTracking: "Caricamento tracciamenti...",
        loadingGeneric: "Caricamento...",
        noTrackedActivities: "Non ci sono attività tracciate per questo giorno",
        confirmDeleteTitle: "Conferma Eliminazione",
        confirmDeleteMessage: "Sei sicuro di voler eliminare il tracciamento dell'attività",
        confirmCancel: "Annulla",
        confirmDelete: "Elimina",
        deleteSuccess: "Tracciamento eliminato con successo",
        deleteError: "Errore durante l'eliminazione del tracciamento",
        trackSuccess: "Attività tracciata con successo!",
        trackError: "Errore nel tracciamento dell'attività"
    },
    en: {
        welcome: "LifeTracker ★",
        login: "Login",
        register: "Sign Up",
        email: "Email",
        password: "Password",
        confirmPassword: "Confirm Password",
        loginButton: "Login",
        registerButton: "Sign Up",
        logout: "Logout",
        loggingIn: "Logging in...",
        registering: "Signing up...",
        loginSuccess: "Login successful!",
        registerSuccess: "Registration complete! Check your email to confirm your account.",
        passwordMismatch: "Passwords do not match",
        logoutError: "Logout error: ",
        emailPlaceholder: "your@email.com",
        passwordPlaceholder: "••••••••",
        dashboardTitle: "Dashboard",
        dashboardText: "Welcome to your dashboard! This section is only visible to authenticated users. Here you can manage your account and access all reserved features.",
        userEmail: "Email:",
        googleLogin: "Sign in with Google",
        orDivider: "or",
        usePersonalEmail: "Use your personal email",
        menuHome: "Tracking",
        menuTasks: "Task List",
        menuCalendar: "Calendar",
        menuStats: "Statistics",
        loadingTasks: "Loading tasks...",
        noTasks: "No tasks found",
        tasksSubtitle: "Here is the list of activities available to you that you can track",
        trackedActivities: "Tracked activities",
        addTracking: "Add a tracking",
        loadingCategories: "Loading categories...",
        loadingTracking: "Loading tracking...",
        loadingGeneric: "Loading...",
        noTrackedActivities: "No tracked activities for this day",
        confirmDeleteTitle: "Confirm Deletion",
        confirmDeleteMessage: "Are you sure you want to delete the tracking for activity",
        confirmCancel: "Cancel",
        confirmDelete: "Delete",
        deleteSuccess: "Tracking successfully deleted",
        deleteError: "Error deleting tracking",
        trackSuccess: "Activity tracked successfully!",
        trackError: "Error tracking activity"
    }
};

// Get browser language
function getBrowserLanguage() {
    const lang = navigator.language || navigator.userLanguage;
    return lang.startsWith('it') ? 'it' : 'en';
}

// Get current language
const currentLang = getBrowserLanguage();
const t = translations[currentLang];
